### ISSUE TITLE
[SR-13897] Can't build swift-llbuild2 with development Swift toolchain

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-llbuild#776]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13897      |
   |Radar             | rdar://problem/71914389         |
   |Original Reporter | Davidee (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | llbuild    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a5c2c7c803ccfeebebc1bca5b3ec7d96

  </details>

**Issue Description:**

While working on a reproducer for <https://bugs.swift.org/browse/SR-13895> I was able to get it to reproduce while using swift-llbuild2, but I couldn't dig into the issue myself with a development Swift toolchain since I can't get swift-llbuild2 to build with either a locally build Swift toolchain or the latest development toolchain snapshot from [https://swift.org/download/.](https://swift.org/download/)

 

Logs: <https://gist.github.com/DavidGoldman/933260ebc751ffe486c1537f0af4d8b6>

``` java
❯ swift build                                                                                                                                                                In file included from /Users/davg/dev/github/swift-llbuild2/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/ssl/tls_record.cc:109:In file included from /Users/davg/dev/github/swift-llbuild2/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include/CNIOBoringSSL_ssl.h:149:In file included from /Users/davg/dev/github/swift-llbuild2/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include/CNIOBoringSSL_pem.h:67:In file included from /Users/davg/dev/github/swift-llbuild2/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include/CNIOBoringSSL_x509.h:76:In file included from /Users/davg/dev/github/swift-llbuild2/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include/CNIOBoringSSL_obj.h:62:20:/Users/davg/dev/github/swift-llbuild2/.build/checkouts/swift-nio-ssl/Sources/CNIOBoringSSL/include/CNIOBoringSSL_span.h:139:7: error: missing '#include <stdlib.h>'; 'abort' must be declared before it is used      abort();      ^/Applications/Xcode_12.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:131:7: note: declaration here is not visiblevoid     abort(void) __cold __dead2;         ^
```

**Comment by dmbryson** [comment]
I think this issue is long stale.   llbuild2 successfully builds with recent toolchains.
